import { useQuery } from '@tanstack/react-query'
import { BookOutlined, CloseOutlined, DownloadOutlined, EyeOutlined, FileOutlined, ReadOutlined, SearchOutlined } from '@ant-design/icons'
import { Alert, Button, Card, Empty, Input, InputNumber, Select, Skeleton, Space, Table, Tag, Typography, type TableColumnsType } from 'antd'
import { Link, useSearchParams } from 'react-router-dom'
import { managementApi, type ManagementSubject, type ManagementSubjectDetail } from '../../managementApi'

const number = new Intl.NumberFormat('vi-VN')

export function ManagementSubjectsPage() {
  const [params, setParams] = useSearchParams()
  const subjects = useQuery({ queryKey: ['management', 'subjects'], queryFn: managementApi.subjects })
  const selectedId = params.get('id')
  const detail = useQuery({ queryKey: ['management', 'subject', selectedId], queryFn: () => managementApi.subject(selectedId!), enabled: !!selectedId })
  const update = (values: Record<string, string | undefined>) => { const next = new URLSearchParams(params); Object.entries(values).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); if (!Object.hasOwn(values, 'page')) next.set('page', '1'); setParams(next) }
  if (subjects.isLoading) return <Skeleton active paragraph={{ rows: 15 }} />
  if (subjects.isError || !subjects.data) return <Alert showIcon type="error" title="Không thể tải danh mục môn học" />

  const search = params.get('search') ?? ''; const faculty = params.get('faculty') ?? ''; const status = params.get('status') ?? ''; const creditFrom = Number(params.get('creditFrom') ?? 0); const creditTo = Number(params.get('creditTo') ?? 0); const page = Number(params.get('page') ?? 1)
  const filtered = subjects.data.filter((subject) => (!search || `${subject.subjectCode} ${subject.name}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))) && (!faculty || subject.facultyId === faculty) && (!status || String(subject.isActive) === status) && (!creditFrom || subject.creditPoint >= creditFrom) && (!creditTo || subject.creditPoint <= creditTo))
  const columns: TableColumnsType<ManagementSubject> = [
    { title: 'Mã môn', dataIndex: 'subjectCode', width: 120, sorter: (a, b) => a.subjectCode.localeCompare(b.subjectCode) },
    { title: 'Tên môn', dataIndex: 'name', width: 230, sorter: (a, b) => a.name.localeCompare(b.name) },
    { title: 'Khoa', render: (_, row) => <Space orientation="vertical" size={0}><span>{row.facultyName ?? 'Chưa phân khoa'}</span>{row.facultyCode && <Typography.Text type="secondary">{row.facultyCode}</Typography.Text>}</Space> },
    { title: 'Tín chỉ', dataIndex: 'creditPoint', align: 'center', width: 85 }, { title: 'Tổng giờ', dataIndex: 'totalHours', align: 'center', width: 95, render: (value) => value ?? '—' },
    { title: 'Trạng thái', width: 120, render: (_, row) => <Tag color={row.isActive ? 'green' : 'orange'}>{row.isActive ? 'Đang sử dụng' : 'Tạm ngừng'}</Tag> },
    { title: 'Ghi chú', align: 'center', width: 75, render: (_, row) => row.specialNoteCount ? <Tag>{row.specialNoteCount}</Tag> : '—' },
    { title: '', width: 55, render: (_, row) => <Button icon={<EyeOutlined />} aria-label={`Xem ${row.subjectCode}`} onClick={() => update({ id: row.subjectId, page: String(page) })} /> },
  ]
  const exportCsv = () => { const rows = [['Mã môn', 'Tên môn', 'Khoa', 'Tín chỉ', 'Tổng giờ', 'Trạng thái'], ...filtered.map((item) => [item.subjectCode, item.name, item.facultyName ?? '', item.creditPoint, item.totalHours ?? '', item.isActive ? 'Đang sử dụng' : 'Tạm ngừng'])]; const blob = new Blob([`\uFEFF${rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n')}`], { type: 'text/csv;charset=utf-8' }); const href = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = href; anchor.download = 'danh-muc-mon-hoc.csv'; anchor.click(); URL.revokeObjectURL(href) }

  return <div className="management-page subjects-page"><div className="subject-page-actions"><Typography.Text type="secondary">Tra cứu môn học và đi tới kế hoạch, lớp học phần, tài liệu liên quan.</Typography.Text><Button type="primary" icon={<DownloadOutlined />} onClick={exportCsv}>Xuất CSV</Button></div><Card className="dashboard-panel subject-filters"><Input value={search} allowClear prefix={<SearchOutlined />} placeholder="Tìm theo mã môn hoặc tên môn..." onChange={(event) => update({ search: event.target.value || undefined })} /><Select value={faculty || undefined} allowClear placeholder="Khoa: Tất cả" options={[...new Map(subjects.data.filter((item) => item.facultyId).map((item) => [item.facultyId!, { value: item.facultyId!, label: item.facultyName ?? item.facultyCode ?? 'Chưa xác định' }])).values()]} onChange={(value) => update({ faculty: value })} /><Select value={status || undefined} allowClear placeholder="Trạng thái: Tất cả" options={[{ value: 'true', label: 'Đang sử dụng' }, { value: 'false', label: 'Tạm ngừng' }]} onChange={(value) => update({ status: value })} /><div className="credit-range"><InputNumber min={0} value={creditFrom || null} placeholder="Tín chỉ từ" onChange={(value) => update({ creditFrom: value ? String(value) : undefined })} /><span>–</span><InputNumber min={0} value={creditTo || null} placeholder="Đến" onChange={(value) => update({ creditTo: value ? String(value) : undefined })} /></div><Button icon={<CloseOutlined />} onClick={() => setParams(new URLSearchParams())}>Xóa bộ lọc</Button></Card><div className="subjects-grid"><Card className="dashboard-panel subject-list" title={<span>Danh sách môn học <Tag>{number.format(filtered.length)}</Tag></span>}><Table rowKey="subjectId" columns={columns} dataSource={filtered} scroll={{ x: 950 }} pagination={{ current: page, pageSize: 10, total: filtered.length, showSizeChanger: true }} onChange={(pagination) => update({ page: String(pagination.current ?? 1) })} onRow={(row) => ({ onClick: () => update({ id: row.subjectId, page: String(page) }) })} rowClassName={(row) => row.subjectId === selectedId ? 'selected-subject-row' : ''} /></Card><Card className="dashboard-panel subject-detail" title="Chi tiết môn học">{!selectedId ? <Empty description="Chọn một môn học để xem chi tiết" /> : detail.isLoading ? <Skeleton active /> : detail.isError || !detail.data ? <Alert showIcon type="error" title="Không thể tải chi tiết môn học" /> : <SubjectProfile subject={detail.data} />}</Card></div></div>
}

function SubjectProfile({ subject }: { subject: ManagementSubjectDetail }) {
  const cards = [{ icon: <ReadOutlined />, label: 'Kế hoạch có môn', value: subject.planCount, to: `/management/education/plans?subjectId=${subject.subjectId}` }, { icon: <BookOutlined />, label: 'Lớp học phần', value: subject.classCount, to: `/management/teaching/classes?search=${encodeURIComponent(subject.subjectCode)}` }, { icon: <FileOutlined />, label: 'Tài liệu', value: subject.documentCount }, { icon: <FileOutlined />, label: 'Ghi chú đặc biệt', value: subject.specialNoteCount }]
  return <Space orientation="vertical" size="large" style={{ width: '100%' }}><div className="subject-detail-heading"><div className="subject-icon"><BookOutlined /></div><div><Typography.Title level={3}>{subject.subjectCode}</Typography.Title><Typography.Text>{subject.name}</Typography.Text></div><Tag color={subject.isActive ? 'green' : 'orange'}>{subject.isActive ? 'Đang sử dụng' : 'Tạm ngừng'}</Tag></div><section className="subject-info-grid"><span>Mã môn<b>{subject.subjectCode}</b></span><span>Tên môn<b>{subject.name}</b></span><span>Khoa<b>{subject.facultyName ?? 'Chưa phân khoa'}</b></span><span>Mã khoa<b>{subject.facultyCode ?? '—'}</b></span><span>Tín chỉ<b>{subject.creditPoint}</b></span><span>Tổng giờ<b>{subject.totalHours ?? 'Chưa xác định'}</b></span></section><section><Typography.Title level={5}>Ghi chú</Typography.Title><Typography.Paragraph>{subject.note?.trim() || 'Chưa có ghi chú cho môn học này.'}</Typography.Paragraph></section><div className="subject-link-cards">{cards.map((card) => <Card size="small" key={card.label}><span className="subject-card-icon">{card.icon}</span><Typography.Text>{card.label}</Typography.Text><strong>{number.format(card.value)}</strong>{card.to ? <Link to={card.to}>Xem chi tiết →</Link> : <Typography.Text type="secondary">{card.value ? 'Chưa có trang tra cứu riêng' : 'Chưa có dữ liệu'}</Typography.Text>}</Card>)}</div><div className="subject-quick-links"><Link to={`/management/education/plans?subjectId=${subject.subjectId}`}><Button>Xem kế hoạch đào tạo</Button></Link><Link to={`/management/teaching/classes?search=${encodeURIComponent(subject.subjectCode)}`}><Button type="primary">Xem lớp học phần</Button></Link></div></Space>
}
