export { StudentLoginPage } from './login'
export { StudentDashboardPage } from './overview'
export { StudentProfilePage } from './profile'
export { StudentProgramPage } from './program'
export { StudentSubjectsPage } from './subjects'
export { StudentSchedulePage } from './schedule'
export { StudentAttendancePage } from './attendance'
export { StudentExamResultsPage } from './exam-results'
export { StudentEvaluationsPage } from './evaluations'
export { StudentAnnouncementsPage } from './announcements'
export { StudentDocumentsPage } from './documents'
export { StudentTuitionPage } from './tuition'
export { StudentFormRequestsPage } from './form-requests'
export { AICVBuilderWorkspace, StudentResumeBuilderPage } from './resume-builder/AICVBuilderWorkspace'
