import { useQuery } from '@tanstack/react-query'
import { Alert, Card, Col, Descriptions, Drawer, Empty, Input, List, Progress, Row, Segmented, Space, Spin, Statistic, Table, Tabs, Tag, Typography, type TableColumnsType } from 'antd'
import dayjs from 'dayjs'
import { useMemo, useState, type ReactNode } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { managementApi, type ClassSummary, type ManagementAttendance, type ManagementSchedule, type PlanSummary, type RawResult, type StudentSummary, type SuiteDetail, type SuiteSummary, type TeacherSummary } from './managementApi'

function Page({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <Space direction="vertical" size="large" style={{ width: '100%' }}><div><Typography.Title level={2}>{title}</Typography.Title>{description && <Typography.Text type="secondary">{description}</Typography.Text>}</div>{children}</Space> }
function State<T>({ query, children }: { query: { isLoading: boolean; isError: boolean; data?: T }; children: (data: T) => ReactNode }) { if (query.isLoading) return <div className="center-state"><Spin /></div>; if (query.isError) return <Alert type="error" showIcon message="Không thể tải dữ liệu quản trị" />; if (!query.data) return <Empty />; return <>{children(query.data)}</> }
const dt = (value: string) => dayjs(value).format('DD/MM/YYYY HH:mm')
const raw = (value?: number | null) => value == null ? 'Chưa xác định' : String(value)

function ManagedTable<T extends object>({ data, rowKey, columns, onRow }: { data: T[]; rowKey: string; columns: TableColumnsType<T>; onRow?: (row: T) => React.HTMLAttributes<HTMLElement> }) {
  const [params, setParams] = useSearchParams()
  const search = params.get('search') ?? ''
  const page = Number(params.get('page') ?? '1')
  const pageSize = Number(params.get('pageSize') ?? '20')
  const filtered = useMemo(() => !search ? data : data.filter((item) => JSON.stringify(item).toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))), [data, search])
  return <Space direction="vertical" style={{ width: '100%' }}><Input.Search aria-label="Tìm kiếm danh sách" allowClear value={search} placeholder="Tìm kiếm..." onChange={(event) => { const next = new URLSearchParams(params); if (event.target.value) next.set('search', event.target.value); else next.delete('search'); next.set('page', '1'); setParams(next) }} /><Table<T> rowKey={rowKey} columns={columns} dataSource={filtered} onRow={onRow} scroll={{ x: 900 }} pagination={{ current: page, pageSize, total: filtered.length, showSizeChanger: true }} onChange={(pagination, _filters, sorter) => { const next = new URLSearchParams(params); next.set('page', String(pagination.current ?? 1)); next.set('pageSize', String(pagination.pageSize ?? 20)); if (!Array.isArray(sorter) && sorter.field) { next.set('sortBy', String(sorter.field)); next.set('sortDirection', sorter.order === 'descend' ? 'desc' : 'asc') } setParams(next) }} /></Space>
}

export function ManagementDashboardPage() {
  const query = useQuery({ queryKey: ['management', 'dashboard'], queryFn: managementApi.dashboard })
  return <Page title="Tổng quan trường" description="Chỉ số quan sát được từ dữ liệu hiện có; không tính tỷ lệ đậu hoặc tiến độ tín chỉ."><State query={query}>{(d) => <><Row gutter={[16, 16]}>{[['Sinh viên', d.students, '/management/people/students'], ['Giảng viên', d.teachers, '/management/people/teachers'], ['Môn học', d.subjects, '/management/education/subjects'], ['Lớp học phần', d.classes, '/management/teaching/classes'], ['Lịch học', d.schedules, '/management/teaching/schedule'], ['Bản ghi điểm danh', d.attendanceRecords, '/management/teaching/attendance']].map(([label, value, link]) => <Col xs={24} sm={12} xl={8} key={String(label)}><Link to={String(link)}><Card hoverable><Statistic title={String(label)} value={Number(value)} /></Card></Link></Col>)}</Row><Card title="Phân bố sinh viên theo khoa"><List dataSource={d.studentsByFaculty} locale={{ emptyText: 'Chưa có dữ liệu phân bố' }} renderItem={(item) => <List.Item><div style={{ width: '100%' }}><div>{item.name} · {item.count}</div><Progress percent={d.students ? Math.round(item.count / d.students * 100) : 0} showInfo={false} /></div></List.Item>} /></Card><Alert type="info" showIcon message="Không hiển thị pass-rate, credit-progress hoặc attendance-rate vì chưa có quy tắc xác nhận." /></>}</State></Page>
}

export function ManagementStudentsPage() { const query = useQuery({ queryKey: ['management', 'students'], queryFn: managementApi.students }); const [selected, setSelected] = useState<StudentSummary>(); const columns: TableColumnsType<StudentSummary> = [{ title: 'MSSV', dataIndex: 'studentCode', sorter: true }, { title: 'Họ tên', dataIndex: 'fullName', render: (v) => v ?? 'Chưa có dữ liệu' }, { title: 'Ngành', render: (_, r) => `${r.majorCode} · ${r.majorName}` }, { title: 'Khoa', dataIndex: 'facultyName', render: (v) => v ?? 'Chưa có khoa' }, { title: 'Niên khóa', dataIndex: 'academicYearName' }, { title: 'Trạng thái thô', dataIndex: 'rawStudyStatus', render: raw }]; return <Page title="Sinh viên"><State query={query}>{(items) => <ManagedTable data={items} rowKey="studentId" columns={columns} onRow={(row) => ({ onClick: () => setSelected(row) })} />}</State><Drawer title="Chi tiết sinh viên" open={!!selected} onClose={() => setSelected(undefined)}>{selected && <Descriptions column={1}><Descriptions.Item label="MSSV">{selected.studentCode}</Descriptions.Item><Descriptions.Item label="Họ tên">{selected.fullName ?? 'Chưa có dữ liệu'}</Descriptions.Item><Descriptions.Item label="Ngành">{selected.majorName}</Descriptions.Item><Descriptions.Item label="Khoa">{selected.facultyName ?? 'Chưa có'}</Descriptions.Item><Descriptions.Item label="Niên khóa">{selected.academicYearName}</Descriptions.Item><Descriptions.Item label="Trạng thái thô">{raw(selected.rawStudyStatus)}</Descriptions.Item></Descriptions>}</Drawer></Page> }
export function ManagementTeachersPage() { const query = useQuery({ queryKey: ['management', 'teachers'], queryFn: managementApi.teachers }); const columns: TableColumnsType<TeacherSummary> = [{ title: 'Họ tên', dataIndex: 'fullName', render: (v) => v ?? 'Chưa có dữ liệu' }, { title: 'Khoa', render: (_, r) => `${r.facultyCode} · ${r.facultyName}` }, { title: 'Cờ trưởng khoa', dataIndex: 'isHeadOfFaculty', render: (v) => v ? 'Có' : 'Không' }, { title: 'Số lớp liên kết', dataIndex: 'classCount' }, { title: 'Môn giảng dạy', dataIndex: 'subjectNames', render: (v: string[]) => v.join(', ') || 'Chưa có' }]; return <Page title="Giảng viên" description="Không suy diễn học hàm, học vị hoặc chức danh."><State query={query}>{(items) => <ManagedTable data={items} rowKey="teacherFacultyId" columns={columns} />}</State></Page> }
export function ManagementPlansPage() { const query = useQuery({ queryKey: ['management', 'plans'], queryFn: managementApi.plans }); const columns: TableColumnsType<PlanSummary> = [{ title: 'Ngành', render: (_, r) => `${r.majorCode} · ${r.majorName}` }, { title: 'Niên khóa', dataIndex: 'academicYearName' }, { title: 'Học kỳ', dataIndex: 'semester' }, { title: 'Khoảng thời gian', render: (_, r) => `${dayjs(r.startDate).format('DD/MM/YYYY')} – ${dayjs(r.endDate).format('DD/MM/YYYY')}` }, { title: 'Số môn trong kế hoạch', dataIndex: 'subjectCount' }]; return <Page title="Kế hoạch học tập theo ngành" description="Không khẳng định phiên bản chương trình hoặc môn bắt buộc/tự chọn."><State query={query}>{(items) => <ManagedTable data={items} rowKey="planId" columns={columns} />}</State></Page> }
export function ManagementClassesPage() { const query = useQuery({ queryKey: ['management', 'classes'], queryFn: managementApi.classes }); const columns: TableColumnsType<ClassSummary> = [{ title: 'Lớp học phần', dataIndex: 'className' }, { title: 'Môn', render: (_, r) => `${r.subjectCode} · ${r.subjectName}` }, { title: 'Khoa (qua môn)', dataIndex: 'facultyName', render: (v) => v ?? 'Chưa có' }, { title: 'Giảng viên', dataIndex: 'teacherNames', render: (v: string[]) => v.join(', ') || 'Chưa có thông tin giảng viên' }, { title: 'Phòng mặc định', dataIndex: 'defaultRoom', render: (v) => v ?? 'Chưa có' }, { title: 'Sinh viên', dataIndex: 'studentCount' }]; return <Page title="Lớp học phần" description="Lớp giảng dạy môn học, không phải lớp hành chính."><State query={query}>{(items) => <ManagedTable data={items} rowKey="classId" columns={columns} />}</State></Page> }

function WeekView({ items }: { items: ManagementSchedule[] }) { const [day, setDay] = useState<number>(dayjs().day()); const days = [1,2,3,4,5,6,0]; return <><div className="schedule-desktop">{days.map((d) => <section className="schedule-day" key={d}><strong>{d === 0 ? 'Chủ nhật' : `Thứ ${d + 1}`}</strong>{items.filter((i) => dayjs(i.startDateTime).day() === d).map((i) => <Card size="small" key={i.scheduleId} title={`${i.subjectCode} · ${i.className}`}>{dayjs(i.startDateTime).format('HH:mm')} · {i.roomName ?? 'Chưa có phòng'}<br />{i.teacherName ?? 'Chưa có thông tin giảng viên'}</Card>)}</section>)}</div><div className="schedule-mobile"><Segmented block value={day} onChange={(v) => setDay(Number(v))} options={days.map((d) => ({ value: d, label: d === 0 ? 'CN' : `T${d + 1}` }))} />{items.filter((i) => dayjs(i.startDateTime).day() === day).map((i) => <Card key={i.scheduleId}>{i.subjectName} · {dt(i.startDateTime)}</Card>)}</div></> }
export function ManagementSchedulePage() { const query = useQuery({ queryKey: ['management', 'schedule'], queryFn: managementApi.schedule }); return <Page title="Lịch giảng dạy theo tuần"><State query={query}>{(items) => items.length ? <WeekView items={items} /> : <Empty />}</State></Page> }
export function ManagementAttendancePage() { const query = useQuery({ queryKey: ['management', 'attendance'], queryFn: managementApi.attendance }); const columns: TableColumnsType<ManagementAttendance> = [{ title: 'Môn', render: (_, r) => `${r.subjectCode} · ${r.subjectName}` }, { title: 'Lớp', dataIndex: 'className' }, { title: 'Buổi', dataIndex: 'startDateTime', render: dt }, { title: 'Trạng thái số thô', dataIndex: 'rawStatus', render: (v) => <Tag>{v}</Tag> }, { title: 'Cờ cảnh báo', render: (_, r) => r.firstWarning || r.secondWarning ? 'Có' : 'Không' }]; return <Page title="Khám phá điểm danh" description="Không gán nhãn trạng thái và không tính tỷ lệ điểm danh."><State query={query}>{(items) => <ManagedTable data={items} rowKey="attendanceId" columns={columns} />}</State></Page> }

export function ManagementResultsPage() { const list = useQuery({ queryKey: ['management', 'results'], queryFn: managementApi.results }); const summary = useQuery({ queryKey: ['management', 'result-summary'], queryFn: managementApi.resultSummary }); const columns: TableColumnsType<RawResult> = [{ title: 'Kỳ thi', dataIndex: 'examName' }, { title: 'Ngày thi', dataIndex: 'examDate', render: dt }, { title: 'Kết quả thô', dataIndex: 'rawResult', render: raw }, { title: 'Tổng hợp thô', dataIndex: 'rawCombinedResult', render: raw }, { title: 'Mô tả nguồn', dataIndex: 'description', render: (v) => v ?? 'Chưa xác định' }]; return <Page title="Kết quả thi thô" description="Thống kê mô tả, không suy diễn đậu/rớt."><State query={summary}>{(s) => <Row gutter={16}><Col span={6}><Card><Statistic title="Bản ghi" value={s.recordCount} /></Card></Col><Col span={6}><Card><Statistic title="Có Result" value={s.resultValueCount} /></Card></Col><Col span={6}><Card><Statistic title="Min thô" value={raw(s.minimumRawResult)} /></Card></Col><Col span={6}><Card><Statistic title="Max thô" value={raw(s.maximumRawResult)} /></Card></Col></Row>}</State><State query={list}>{(items) => <ManagedTable data={items} rowKey="examResultId" columns={columns} />}</State></Page> }

export function ManagementQuestionSuitesPage() { const query = useQuery({ queryKey: ['management', 'suites'], queryFn: managementApi.suites }); const [id, setId] = useState<string>(); const detail = useQuery({ queryKey: ['management', 'suite', id], queryFn: () => managementApi.suite(id!), enabled: !!id }); const columns: TableColumnsType<SuiteSummary> = [{ title: 'Bộ câu hỏi', dataIndex: 'name' }, { title: 'Ngày tạo', dataIndex: 'creationTime', render: dt }, { title: 'Số câu hỏi', dataIndex: 'questionCount' }]; return <Page title="Ngân hàng câu hỏi" description="Duyệt theo Bộ câu hỏi → Câu hỏi → Đáp án."><State query={query}>{(items) => <ManagedTable data={items} rowKey="questionSuiteId" columns={columns} onRow={(row) => ({ onClick: () => setId(row.questionSuiteId) })} />}</State><Drawer size={720} title="Xem bộ câu hỏi" open={!!id} onClose={() => setId(undefined)}><State<SuiteDetail> query={detail}>{(suite) => <><Typography.Title level={4}>{suite.name}</Typography.Title><Tabs items={suite.questions.map((q, index) => ({ key: q.questionId, label: `Câu ${index + 1}`, children: <Card title={q.questionText}><List dataSource={q.answers} renderItem={(answer) => <List.Item><Tag color={answer.isSourceMarkedAnswer ? 'green' : 'default'}>{answer.isSourceMarkedAnswer ? 'Được đánh dấu trong nguồn' : 'Phương án'}</Tag>{answer.answerText}</List.Item>} /></Card> }))} /></>}</State></Drawer></Page> }
