import { useQuery } from '@tanstack/react-query'
import { CloseOutlined, DownloadOutlined, EyeOutlined, LeftOutlined, RightOutlined } from '@ant-design/icons'
import { Alert, Button, Card, DatePicker, Empty, Select, Skeleton, Space, Statistic, Table, Tabs, Tag, Typography, type TableColumnsType } from 'antd'
import dayjs, { type Dayjs } from 'dayjs'
import { Link, useSearchParams } from 'react-router-dom'
import { managementApi, type ManagementRoom, type TeachingSchedule } from '../../managementApi'
import { SCHEDULE_TYPE_MAP } from '../../../../shared/utils/enumMappers'

const number = new Intl.NumberFormat('vi-VN')
const mondayOf = (value: Dayjs) => value.subtract((value.day() + 6) % 7, 'day').startOf('day')
const typeInfo = (value?: number | null) => value == null ? { label: 'Chưa xác định', color: 'default' } : SCHEDULE_TYPE_MAP[value] ?? { label: `Loại ${value}`, color: 'default' }

export function ManagementRoomsSchedulePage() {
  const [params, setParams] = useSearchParams()
  const schedules = useQuery({ queryKey: ['management', 'teaching-schedule'], queryFn: managementApi.teachingSchedule })
  const rooms = useQuery({ queryKey: ['management', 'rooms'], queryFn: managementApi.rooms })
  const update = (values: Record<string, string | undefined>) => { const next = new URLSearchParams(params); Object.entries(values).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); setParams(next) }
  if (schedules.isLoading || rooms.isLoading) return <Skeleton active paragraph={{ rows: 15 }} />
  if (schedules.isError || rooms.isError || !schedules.data || !rooms.data) return <Alert showIcon type="error" title="Không thể tải phòng và lịch giảng dạy" />

  const fallbackDate = schedules.data.length ? dayjs(schedules.data.at(-1)!.startDateTime) : dayjs()
  const weekStart = mondayOf(params.get('week') ? dayjs(params.get('week')) : fallbackDate); const weekEnd = weekStart.add(6, 'day').endOf('day')
  const roomId = params.get('roomId') ?? ''; const subjectId = params.get('subjectId') ?? ''; const teacherId = params.get('teacherId') ?? ''; const scheduleType = params.get('type') ?? ''; const tab = params.get('tab') ?? 'week'; const page = Number(params.get('page') ?? 1)
  const firstRoomInWeek = schedules.data.find((item) => item.roomId && dayjs(item.startDateTime).isAfter(weekStart.subtract(1, 'millisecond')) && dayjs(item.startDateTime).isBefore(weekEnd.add(1, 'millisecond')))?.roomId
  const selectedRoom = rooms.data.find((room) => room.roomId === (roomId || firstRoomInWeek)) ?? rooms.data[0]
  const filtered = schedules.data.filter((item) => dayjs(item.startDateTime).isAfter(weekStart.subtract(1, 'millisecond')) && dayjs(item.startDateTime).isBefore(weekEnd.add(1, 'millisecond')) && (!roomId || item.roomId === roomId) && (!subjectId || item.subjectId === subjectId) && (!teacherId || item.teacherFacultyId === teacherId) && (!scheduleType || String(item.scheduleType) === scheduleType))
  const conflicts = new Set(filtered.filter((item, index) => item.roomId && filtered.some((other, otherIndex) => index !== otherIndex && other.roomId === item.roomId && dayjs(item.startDateTime).isBefore(dayjs(other.endDateTime)) && dayjs(item.endDateTime).isAfter(dayjs(other.startDateTime)))).map((item) => item.scheduleId))
  const allRoomWeekSchedules = selectedRoom ? schedules.data.filter((item) => item.roomId === selectedRoom.roomId && dayjs(item.startDateTime).isAfter(weekStart.subtract(1, 'millisecond')) && dayjs(item.startDateTime).isBefore(weekEnd.add(1, 'millisecond'))) : []
  const options = { rooms: rooms.data.map((item) => ({ value: item.roomId, label: item.name })), subjects: [...new Map(schedules.data.map((item) => [item.subjectId, { value: item.subjectId, label: `${item.subjectCode} · ${item.subjectName}` }])).values()], teachers: [...new Map(schedules.data.filter((item) => item.teacherFacultyId).map((item) => [item.teacherFacultyId!, { value: item.teacherFacultyId!, label: item.teacherName ?? 'Chưa xác định' }])).values()] }
  const columns: TableColumnsType<TeachingSchedule> = [{ title: 'Thời gian', render: (_, row) => <><b>{dayjs(row.startDateTime).format('DD/MM/YYYY')}</b><br />{dayjs(row.startDateTime).format('HH:mm')} – {dayjs(row.endDateTime).format('HH:mm')}</> }, { title: 'Môn học / Lớp', render: (_, row) => <Space orientation="vertical" size={0}><Link to={`/management/education/subjects?id=${row.subjectId}`}>{row.subjectCode} · {row.subjectName}</Link><Link to={`/management/teaching/classes?id=${row.classId}`}>{row.className}</Link></Space> }, { title: 'Loại', render: (_, row) => { const info = typeInfo(row.scheduleType); return <Tag color={info.color}>{info.label}</Tag> } }, { title: 'Phòng', render: (_, row) => row.roomId ? <Button type="link" onClick={() => update({ roomId: row.roomId! })}>{row.roomName}</Button> : 'Chưa xếp' }, { title: 'Giảng viên', render: (_, row) => row.teacherFacultyId ? <Link to={`/management/people/teachers?id=${row.teacherFacultyId}`}>{row.teacherName ?? 'Chưa xác định'}</Link> : 'Chưa phân công' }, { title: 'Sĩ số', render: (_, row) => row.roomCapacity ? `${row.studentCount}/${row.roomCapacity}` : row.studentCount }, { title: 'Ghi chú', render: (_, row) => conflicts.has(row.scheduleId) ? <Tag color="red">Trùng phòng</Tag> : row.note?.trim() || '—' }, { title: '', render: (_, row) => <Link to={`/management/teaching/classes?id=${row.classId}`}><Button icon={<EyeOutlined />} /></Link> }]
  const exportCsv = () => { const rows = [['Thời gian', 'Môn', 'Lớp', 'Phòng', 'Giảng viên', 'Loại', 'Sĩ số'], ...filtered.map((item) => [item.startDateTime, item.subjectCode, item.className, item.roomName ?? '', item.teacherName ?? '', typeInfo(item.scheduleType).label, item.studentCount])]; const blob = new Blob([`\uFEFF${rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n')}`], { type: 'text/csv;charset=utf-8' }); const href = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = href; anchor.download = 'lich-giang-day.csv'; anchor.click(); URL.revokeObjectURL(href) }

  const filters = <div className="schedule-toolbar"><Button icon={<LeftOutlined />} onClick={() => update({ week: weekStart.subtract(7, 'day').format('YYYY-MM-DD') })} /><DatePicker value={weekStart} onChange={(date) => date && update({ week: mondayOf(date).format('YYYY-MM-DD') })} /><Button icon={<RightOutlined />} onClick={() => update({ week: weekStart.add(7, 'day').format('YYYY-MM-DD') })} /><Select value={roomId || undefined} allowClear placeholder="Phòng: Tất cả" options={options.rooms} onChange={(value) => update({ roomId: value })} /><Select value={subjectId || undefined} allowClear showSearch placeholder="Môn học / Lớp" options={options.subjects} onChange={(value) => update({ subjectId: value })} /><Select value={teacherId || undefined} allowClear showSearch placeholder="Giảng viên" options={options.teachers} onChange={(value) => update({ teacherId: value })} /><Select value={scheduleType || undefined} allowClear placeholder="Loại lịch" options={Object.entries(SCHEDULE_TYPE_MAP).map(([value, info]) => ({ value, label: info.label }))} onChange={(value) => update({ type: value })} /><Button icon={<CloseOutlined />} onClick={() => setParams(new URLSearchParams({ week: weekStart.format('YYYY-MM-DD') }))}>Xóa lọc</Button></div>
  return <div className="management-page rooms-schedule-page"><div className="schedule-page-actions"><Typography.Text type="secondary">Tra cứu việc sử dụng phòng và lịch giảng dạy của lớp học phần, giảng viên.</Typography.Text><Button type="primary" icon={<DownloadOutlined />} onClick={exportCsv}>Xuất CSV</Button></div><div className="rooms-schedule-grid"><Card className="dashboard-panel schedule-main"><Tabs activeKey={tab} onChange={(value) => update({ tab: value })} items={[{ key: 'week', label: 'Lịch tuần', children: <>{filters}<WeekGrid start={weekStart} items={filtered} conflicts={conflicts} /></> }, { key: 'list', label: 'Danh sách lịch', children: <>{filters}<Table rowKey="scheduleId" columns={columns} dataSource={filtered} scroll={{ x: 1100 }} pagination={{ current: page, pageSize: 10, total: filtered.length }} onChange={(pagination) => update({ page: String(pagination.current ?? 1) })} /></> }, { key: 'rooms', label: 'Danh mục phòng', children: <Table rowKey="roomId" dataSource={rooms.data} columns={[{ title: 'Phòng', dataIndex: 'name' }, { title: 'Số chỗ', dataIndex: 'numberOfSeats' }, { title: 'Số lịch', dataIndex: 'scheduleCount' }, { title: 'Lớp dùng mặc định', dataIndex: 'defaultClassCount' }, { title: '', render: (_, row: ManagementRoom) => <Button onClick={() => update({ roomId: row.roomId })}>Xem lịch</Button> }]} pagination={{ pageSize: 10 }} />}]} /></Card><RoomDetail room={selectedRoom} items={allRoomWeekSchedules} weekStart={weekStart} conflicts={conflicts} /></div></div>
}

function WeekGrid({ start, items, conflicts }: { start: Dayjs; items: TeachingSchedule[]; conflicts: Set<string> }) {
  const days = Array.from({ length: 7 }, (_, index) => start.add(index, 'day'))
  return <><div className="management-week-grid">{days.map((day) => <section key={day.format('YYYY-MM-DD')}><header><b>{day.day() === 0 ? 'Chủ nhật' : `Thứ ${day.day() + 1}`}</b><span>{day.format('DD/MM')}</span></header>{items.filter((item) => dayjs(item.startDateTime).isSame(day, 'day')).map((item) => { const info = typeInfo(item.scheduleType); return <Link className={`week-schedule-card ${conflicts.has(item.scheduleId) ? 'conflict' : ''}`} key={item.scheduleId} to={`/management/teaching/classes?id=${item.classId}`}><b>{dayjs(item.startDateTime).format('HH:mm')} – {dayjs(item.endDateTime).format('HH:mm')}</b><span>{item.subjectCode} · {item.className}</span><span>{item.roomName ?? 'Chưa xếp phòng'}</span><span>{item.teacherName ?? 'Chưa phân công'}</span><Tag color={info.color}>{info.label}</Tag></Link>})}</section>)}</div><Card className="weekly-list-card" title={<span>Danh sách lịch trong tuần <Tag>{items.length}</Tag></span>}><div className="weekly-compact-list">{items.map((item) => <Link key={item.scheduleId} to={`/management/teaching/classes?id=${item.classId}`}><span><b>{dayjs(item.startDateTime).format('DD/MM/YYYY')}</b><small>{dayjs(item.startDateTime).format('HH:mm')} – {dayjs(item.endDateTime).format('HH:mm')}</small></span><span><b>{item.subjectCode} · {item.subjectName}</b><small>{item.className}</small></span><span>{typeInfo(item.scheduleType).label}</span><span>{item.roomName ?? 'Chưa xếp'}</span><span>{item.teacherName ?? 'Chưa phân công'}</span><span>{item.roomCapacity ? `${item.studentCount}/${item.roomCapacity}` : item.studentCount}</span>{conflicts.has(item.scheduleId) ? <Tag color="red">Trùng lịch</Tag> : <RightOutlined />}</Link>)}</div></Card></>
}

function RoomDetail({ room, items, weekStart, conflicts }: { room?: ManagementRoom; items: TeachingSchedule[]; weekStart: Dayjs; conflicts: Set<string> }) {
  if (!room) return <Card className="dashboard-panel room-detail"><Empty description="Chưa có dữ liệu phòng" /></Card>
  return <Card className="dashboard-panel room-detail" title="Chi tiết phòng"><Space orientation="vertical" size="large" style={{ width: '100%' }}><div className="room-detail-heading"><div className="room-icon">▣</div><div><Typography.Title level={3}>{room.name}</Typography.Title><Typography.Text>{number.format(room.numberOfSeats)} chỗ</Typography.Text></div></div><div className="room-stats"><Statistic title="Sức chứa" value={room.numberOfSeats} suffix="chỗ" /><Statistic title="Tổng lịch" value={room.scheduleCount} /><Statistic title="Lớp dùng mặc định" value={room.defaultClassCount} /></div><Alert type="info" showIcon message="Database chưa có loại phòng, thiết bị, tòa nhà hoặc ghi chú phòng." /><Typography.Title level={5}>Lịch sử dụng trong tuần ({weekStart.format('DD/MM')} – {weekStart.add(6, 'day').format('DD/MM')})</Typography.Title>{items.length ? <div className="room-usage-list">{items.map((item) => <Link key={item.scheduleId} to={`/management/teaching/classes?id=${item.classId}`}><span>{dayjs(item.startDateTime).format('DD/MM HH:mm')} – {dayjs(item.endDateTime).format('HH:mm')}</span><b>{item.subjectCode} · {item.className}</b><span>{item.teacherName ?? 'Chưa phân công'}</span>{conflicts.has(item.scheduleId) && <Tag color="red">Trùng lịch</Tag>}</Link>)}</div> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="Phòng không có lịch trong tuần này" />}</Space></Card>
}
